token: "YOUR_BOT_TOKEN"
webhook_domain: "YOUR_WEBHOOK_DOMAIN"
webhook_port: "8080"
webhook_secret: "YOUR_BOT_WEBHOOK_SECRET"
webapp_domain: "YOUR_WEBAPP_DOMAIN"
webapp_port: "8081"
db_dsn: "postgresql://user:pass@localhost:5432/my_db?sslmode=disable"
static_content_path: "./static"
redis_addr: "localhost:6375"
redis_user: "default"
redis_pass: "password"